GET http://localhost:3000/auth/register

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "teste",
    "email": "Juliano@gmail.com",
    "password": "pariacaria",
    "confirmpassword": "pariacaria"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "Juliano@gmail.com",
    "password": "pariacaria"
}
###
GET http://localhost:3000/user/66d38373739955419a0e1b88
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDM4MzczNzM5OTU1NDE5YTBlMWI4OCIsImlhdCI6MTcyNTE0NDAxNX0.v05TV2RkpblS_xBZZg5DaQlvgPIdfiogkWjB7SCso0A

